export enum ResourcePanelType {
  DEFAULT = "DEFAULT",
  NONE = "NONE",

  PROPERTIES = "PROPERTIES",
  LINKS = "LINKS",
  ACTIVITY = "ACTIVITY",
  METADATA = "METADATA",

  OUTLINE = "OUTLINE",
  BOOKMARKS = "BOOKMARKS",
  SIDENOTES = "SIDENOTES",

  ANALYTICS = "ANALYTICS",
  INFO = "INFO",
  SUB = "SUB",
  TASKS = "TASKS"
}
