<script lang="ts">
  import Table2 from "$lib/client/elements/table/Table2.svelte";
  import { InputStyle } from "$lib/client/types/input.type";
  import { Resource } from "$lib/client/components/flux/resourceStores/resource.enum";
  import { Size } from "$lib/client/types/size.enum";
  import {
    TableCellType,
    type TableColumn
  } from "$lib/client/types/table.type";
  import { enumToString } from "$lib/shared/utils/text.utils";
  import { generateResourceId } from "$lib/client/components/flux/flux.utils";

  import { PropertyType, type IProperty } from "./property.type";
  import {
    autoPropertiesGroupLabel,
    metaPropertyOptions,
    propertyEditorStore,
    propertyOptions,
    propertyStore
  } from "./property.store";
  import {
    ActiveCollectionStore,
    type IActiveCollectionStore
  } from "../collection.store";
  import ModalFooter from "$lib/client/components/modal/ModalFooter.svelte";
  import { MemotronAction } from "../../memotronAction.enum";
  import type { OmitForCaptureWithId } from "$lib/client/components/flux/resourceStores/resource.type";
  import type { IRecordId } from "$lib/client/types/data.type";
  import { onMount } from "svelte";
  import Text from "$lib/client/elements/text/Text.svelte";
  import { TextStyle } from "$lib/client/types/text.enum";
  import { logger } from "$lib/client/components/debug/logger.client";
  import ComponentBaseLayer from "$lib/client/layout/layers/ComponentBaseLayer.svelte";
  export let id: IRecordId | undefined = undefined;
  let collection: IActiveCollectionStore | undefined = id
    ? ActiveCollectionStore.resolve(id)
    : undefined;
  let tableId = "properties-table";
  let columns: TableColumn[] = [
    {
      label: "Type",
      key: "type",
      type: TableCellType.DROPDOWN,
      style: InputStyle.BORDERED,
      groups: [
        {
          id: autoPropertiesGroupLabel,
          label: autoPropertiesGroupLabel,
          info: {
            body: "These properties are automatically generated by the system when the node entry is created.",
            link: "faqs",
            size: Size.xs
          },
          order: 0
        }
      ],
      options: [...propertyOptions, ...metaPropertyOptions]
    },
    {
      label: "Label",
      key: "label",
      type: TableCellType.TEXT_INPUT,
      placeholder: (row: any) => {
        return enumToString(row.type);
      }
    },
    {
      label: "Configuration",
      key: "config",
      width: 1.25,
      type: TableCellType.CUSTOM,
      component: "propertyConfig"
    },
    {
      label: "Always visible",
      key: "isShowOnNodePage",
      width: 0.5,
      type: TableCellType.TOGGLE
    },
    {
      label: "Capture",
      key: "isShowOnCapture",
      width: 0.4,
      type: TableCellType.TOGGLE,
      disabledCriteria: (row: any) =>
        row.type === PropertyType.CREATED_TIME ||
        row.type === PropertyType.MODIFIED_TIME ||
        row.type === PropertyType.LOCATION
    }
  ];

  async function onAdd() {
    const newProperty: OmitForCaptureWithId<IProperty> = {
      id: generateResourceId(Resource.property),
      label: "",
      isShowOnNodePage: false,
      isShowOnCapture: false,
      type: PropertyType.TEXT,
      order: $propertyEditorStore.length
    };
    $propertyEditorStore = [...$propertyEditorStore, newProperty];
    if (collection) {
      await propertyStore.create([newProperty]);
    }
  }
  onMount(async () => {
    if (collection && (!$collection || $collection.label)) {
      await collection.init();
    }
  });

  function resolveTitle(collection: IActiveCollectionStore | undefined) {
    return collection
      ? ($collection?.label ?? "Untitled") + " - edit properties"
      : "Edit properties";
  }

  function onRearrange(
    event: CustomEvent<{ from: number; to: number; listId: string }>
  ) {
    logger.log({ at: "PropertiesEditor.onReorder", event });
    const { from, to, listId } = event.detail;
    if (!from || !to || !listId || listId !== tableId) return;
    const [movedItem] = $propertyEditorStore.splice(from, 1);
    $propertyEditorStore.splice(to, 0, movedItem);
    $propertyEditorStore = $propertyEditorStore;
  }
</script>

<div class="flex flex-col justify-between gap-4 w-full h-full text-b2">
  <div class="flex flex-col gap-4">
    <Text content={resolveTitle(collection)} style={TextStyle.PANEL_HEADING} />
    <Table2
      id={tableId}
      isStyled={true}
      addAction="add property"
      actions={[
        { action: "remove", index: 0 },
        { action: "rearrange", index: 1 }
      ]}
      {columns}
      bind:data={$propertyEditorStore}
      on:add={onAdd}
      on:rearrange={onRearrange}
    />
  </div>
  <ModalFooter
    action={MemotronAction.EDIT_COLLECTION_PROPERTIES}
    primaryAction={collection
      ? {
          label: "Save",
          callback: async () => {
            const result = await collection.updateProperties();
            return true;
          }
        }
      : {
          label: "Done"
        }}
    secondaryAction={collection
      ? {
          label: "Cancel"
        }
      : undefined}
  />
</div>

<ComponentBaseLayer hasDragAndDrop={true} />
