apiVersion: pingcap.com/v1alpha1
kind: TidbCluster
metadata:
  name: basic
  namespace: tidb-cluster
spec:
  version: v8.5.0
  timezone: UTC
  pvReclaimPolicy: Delete
  enableDynamicConfiguration: true
  configUpdateStrategy: RollingUpdate
  
  pd:
    replicas: 1
    requests:
      storage: "10Gi"
      cpu: "250m"
      memory: "512Mi"
    limits:
      cpu: "500m"
      memory: "1Gi"
    storageClassName: gp3
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: pd
    nodeSelector:
      dedicated: pd
    config:
      log:
        level: info
      replication:
        enable-placement-rules: true
        location-labels:
          - zone
  
  tikv:
    replicas: 1
    requests:
      storage: "20Gi"
      cpu: "500m"
      memory: "1Gi"
    limits:
      cpu: "1000m"
      memory: "2Gi"
    storageClassName: gp3
    tolerations:
      - effect: NoSchedule
        key: dedicated
        operator: Equal
        value: tikv
    nodeSelector:
      dedicated: tikv
    config:
      log-level: info
      storage:
        reserve-space: "1GB"
      rocksdb:
        max-open-files: 256
        max-background-jobs: 4
      raftdb:
        max-open-files: 256
        max-background-jobs: 2
