export enum AppEvent {
  NONE = "NONE",
  CMD = "CMD",
  EDIT_MODE = "EDIT_MODE",
  SHOW_APPEARANCE_PREVIEW = "SHOW_APPEARANCE_PREVIEW",
  PAGE_MENU_CHANGED = "PAGE_MENU_CHANGED",
  MINIMIZE_POWERPANEL = "MINIMIZE_POWERPANEL",
  POP_DISMISSED = "POP_DISMISSED",
  THINMODE_PANELSWITCH = "THINMODE_PANELSWITCH",
  WINDOW_VISIBILITY_CHANGED = "WINDOW_VISIBILITY_CHANGED",
  WINDOW_CLICKED = "WINDOW_CLICKED",
  WINDOW_RESIZED = "WINDOW_RESIZED",
  USER_LOGIN = "USER_LOGIN",
  USER_SIGNUP = "USER_SIGNUP"
}
