export enum AppEvent {
  NONE,
  SHOW_APPEARANCE_PREVIEW,
  PAGE_MENU_CHANGED,
  MINIMIZE_POWERPANEL,
  POP_DISMISSED,
  THINMODE_PANELSWITCH,
  WINDOW_VISIBILITY_CHANGED,
  WINDOW_CLICKED,
  WINDOW_RESIZED,
  USER_LOGIN,
  USER_SIGNUP,
}
