export enum AppEvent {
  NONE = "NONE",
  CMD = "CMD",
  EDIT_MODE = "EDIT_MODE",
  SHOW_APPEARANCE_PREVIEW = "SHOW_APPEARANCE_PREVIEW",
  PAGE_MENU_CHANGED = "PAGE_MENU_CHANGED",
  MINIMIZE_POWERPANEL = "MINIMIZE_POWERPANEL",
  POP_DISMISSED = "POP_DISMISSED",
  THINMODE_PANELSWITCH = "THINMODE_PANELSWITCH",
  WINDOW_VISIBILITY_CHANGED = "WINDOW_VISIBILITY_CHANGED",
  WINDOW_CLICKED = "WINDOW_CLICKED",
  WINDOW_RESIZED = "WINDOW_RESIZED",
  USER_LOGIN = "USER_LOGIN",
  USER_SIGNUP = "USER_SIGNUP",
  HELP = "HELP",
  SETTINGS = "cp",
  ACCOUNT = "account",
  MANUAL_RUN_DBO = "MANUAL_RUN_DBO",
  TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR",
  MOBILE_TOAST = "MOBILE_TOAST",
  CONFIRMATION = "CONFIRMATION"
}

export enum PlayActionState {
  NOT_STARTED = "NOT_STARTED",
  RUNNING = "RUNNING",
  PAUSED = "PAUSED",
  STOPPED = "STOPPED",
  PREVIEWING = "PREVIEWING",
  PAUSEPREVIEWING="PAUSEPREVIEWING",
  RESUMEPREVIEWING="RESUMEPREVIEWING"
}
