export enum IdentityProvider {
  Google = "google.com",
  Github = "github.com",
  Dribbble = "dribbble.com",
  Stackoverflow = "stackoverflow.com",
  Linkedin = "linkedin.com",
  GenericLink = "generic-link",
  Domain = "www.domain.com",
  Email = "email",
  Twitter = "twitter.com",
  Facebook = "facebook.com",
  Instagram = "instagram.com",
  Youtube = "youtube.com",
  Twitch = "twitch.com",
  Reddit = "reddit.com",
  Medium = "medium.com",
  Devto = "devto",
  Hashnode = "hashnode",
  Producthunt = "producthunt.com",
  Behance = "behance.net",
  Gitlab = "gitlab.com",
  Bitbucket = "bitbucket.org",
  Codepen = "codepen",
  Kaggle = "kaggle.com",
  Kaggle2 = "kaggle2",
  Phone = "phone",
  FiveHundredPx = "500px.com",
}
