export enum Contemporary {
  Notion = "notion",
  Obsidian = "obsidian",
  Capacities = "capacities",
  Roam = "roam",
  Remnote = "remnote",
  Anytype = "anytype",
  Tana = "tana",
  Heptabase = "heptabase",
  Logseq = "logseq",
  Dynalist = "dynalist",
  Ideaflow = "ideaflow",
  AppleNotes = "apple notes",
  ClickupDocs = "clickup docs",
  Gitbook = "gitbook",
  AudioPen = "audioPen",
  Liner = "liner",
  Mymind = "mymind",
  Pocket = "pocket",
  Instapaper = "instapaper",
  Raindrop = "raindrop"
}
