.submodule_auth: &submodule_auth
  before_script:
    - git config --global url."https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab.com/".insteadOf "https://gitlab.com/"

stages:
  - build
  - deploy
.base_build_job:
  <<: *submodule_auth
  stage: build
  image: node:20
  variables:
    NODE_OPTIONS: --max_old_space_size=4096
  script:
    - rm -rf node_modules package-lock.json
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - npm install
    - cat $APP_ENV_VARS > .env
    - npm run build
  artifacts:
    paths:
      - build/
    expire_in: 1 hour
.base_cdk_deploy_job:
  <<: *submodule_auth
  stage: deploy
  image: node:20
  script:
    - npm install -g aws-cdk
    - apt-get update && apt-get install -y awscli
    - export AWS_DEFAULT_REGION="us-east-1"
    - git submodule sync --recursive
    - git submodule update --init --recursive
    - cd lib/deployment
    - rm -rf node_modules package-lock.json
    - npm install
    - cd cdk/staticClient
    - rm -rf node_modules package-lock.json
    - npm install && npm run build
    - cdk deploy --all --require-approval never

#Dev
dev_build_job:
  extends: .base_build_job
  environment: dev
  only:
    - dev-deploy
dev_cdk_deploy_job:
  extends: .base_cdk_deploy_job
  environment: dev
  only:
    - dev-deploy

#Pre
pre_build_job:
  extends: .base_build_job
  environment: pre
  only:
    - pre
pre_cdk_deploy_job:
  extends: .base_cdk_deploy_job
  environment: pre
  only:
    - pre

#Live
live_build_job:
  extends: .base_build_job
  environment: live
  only:
    - live
live_cdk_deploy_job:
  extends: .base_cdk_deploy_job
  environment: live
  only:
    - live
