export enum Action {
  CMD = "CMD",
  MODE_OF_INTERACTION = "MODE_OF_INTERACTION",
  EDIT_MODE = "EDIT_MODE",
  USER_LOGIN = "USER_LOGIN",
  USER_SIGNUP = "USER_SIGNUP",
  HELP = "HELP",
  SETTINGS = "cp",
  ACCOUNT = "account",
  MANUAL_RUN_DBO = "MANUAL_RUN_DBO",
  TOGGLE_SIDEBAR = "TOGGLE_SIDEBAR",
  MOBILE_TOAST = "MOBILE_TOAST",
  CONFIRMATION = "CONFIRMATION",
  ROADMAP = "roadmap",
  PRIVACY_POLICY = "privacy",
  TERMS_OF_SERVICE = "tos",
  GLOBAL_SEARCH = "global-search",
  SHOW_MORE_SHORTCUT_HINTS = "SHOW_MORE_SHORTCUT_HINTS"
}
