export enum EmbedMessage {
  PING = "PING",
  MOUNT = "MOUNT",
  CAMERA = "CAMERA",
  SHEET_MOUNTED = "SHEET_MOUNTED",
  CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS",
  MENU_ITEM_SELECTED = "MENU_ITEM_SELECTED"
}
