export enum EmbedMessage {
  PING = "PING",
  MOUNT = "MOUNT",
  CAMERA = "CAMERA",
  SHEET_MOUNTED = "SHEET_MOUNTED",
  CLEAR_NOTIFICATIONS = "CLEAR_NOTIFICATIONS",
  MENU_ITEM_SELECTED = "MENU_ITEM_SELECTED",
  RESTORE_PURCHASE = "RESTORE_PURCHASE",
  CHECK_SUBSCRIPTION = "CHECK_SUBSCRIPTION",
  MODIFY_SUBSCRIPTION = "MODIFY_SUBSCRIPTION",
  LOCATION = "LOCATION"
}
