const phosphorIcons = [
  // Star variants
  "star",
  "star-half",

  // Navigation and Arrows
  "arrow-left",
  "arrow-right",
  "arrow-up",
  "arrow-down",
  "arrow-up-right",
  "arrow-down-left",
  "arrow-elbow-down-left",
  "arrow-elbow-right-up",
  "arrow-elbow-left-up",
  "arrow-bend-down-left",
  "arrows-left-right",
  "arrows-out",
  "arrows-out-simple",
  "arrows-out-cardinal",
  "arrows-out-line-horizontal",
  "arrows-in-line-horizontal",
  "arrows-clockwise",
  "arrow-line-down",
  "arrow-line-up",
  "arrow-line-left",
  "arrow-line-right",
  "arrow-line-up-right",
  "arrow-line-down-left",
  "arrow-line-down-left",
  "arrow-line-down-right",
  "arrow-u-up-right",
  "arrow-u-up-left",
  "arrow-clockwise",
  "arrow-counter-clockwise",
  "arrow-elbow-down-right",
  "arrow-arc-left",

  //Carets
  "caret-down",
  "caret-up",
  "caret-left",
  "caret-right",
  "caret-circle-up",
  "caret-circle-down",
  "caret-circle-left",
  "caret-circle-right",
  "caret-line-down",
  "caret-line-up",
  "caret-line-left",
  "caret-line-right",
  "caret-double-down",
  "caret-double-up",
  "caret-double-left",
  "caret-double-right",
  "caret-circle-double-down",
  "caret-circle-double-up",
  "caret-circle-double-left",
  "caret-circle-double-right",

  // UI Controls
  "x",
  "x-circle",
  "x-bold",
  "plus",
  "minus-circle",
  "check",
  "check-circle",
  "dots-nine",
  "dots-three-vertical",
  "dots-three",
  "dots-six-vertical",
  "dots-six-vertical-bold",
  "dots-six",
  "dots-three-circle",
  "dots-three-circle-vertical",
  "dots-three-outline",
  "dots-three-outline-vertical",
  // Media and Files
  "image",
  "video",
  "music-note",
  "file",
  "file-pdf",
  "file-csv",
  "file-html",
  "file-txt",
  "file-zip",
  "file-doc",
  "file-ppt",
  "file-xls",

  // Actions
  "crop",
  "highlighter",
  "highlighter-circle",
  "bookmark-simple",
  "bookmarks",
  "download-simple",
  "upload",
  "trash",
  "archive",
  "pencil-simple",
  "pencil-simple-line",
  "eye",
  "eye-slash",
  "copy",
  "link",
  "link-break",
  "link-simple",
  "link-simple-horizontal",
  "link-simple-break",
  "link-simple-horizontal-break",
  "faders",
  "sliders-horizontal",

  // Logos and Brands
  "x-logo",
  "youtube-logo",
  "amazon-logo",
  "discord-logo",
  "markdown-logo",

  // Layout and View
  "table",
  "tabs",
  "squares-four",
  "square-split-horizontal",
  "align-left-simple",
  "align-top-simple",
  "align-right-simple",
  "bounding-box",

  // Status and Info
  "info",
  "question",
  "lock",
  "lock-open",
  "lock-simple",
  "circle",
  "circle-bold",
  "circles-four",

  // Misc
  "book",
  "book-open-text",
  "brain",
  "bird",
  "butterfly",
  "cube",
  "database",
  "globe",
  "graph",
  "house",
  "keyboard",
  "leaf",
  "lightbulb",
  "magic-wand",
  "map-trifold",
  "note",
  "palette",
  "person-simple",
  "rocket",
  "share",
  "tag",
  "terminal",
  "text",
  "chat",
  "chat-teardrop-text",
  "clock",
  "clock-countdown",
  "clock-afternoon",
  "clock-clockwise",
  "clock-counter-clockwise",
  "git-fork",
  "gradient",
  "list",
  "magnifying-glass",
  "magnifying-glass-minus",
  "magnifying-glass-plus",
  "microphone",
  "pause",
  "play",
  "camera",
  "at",
  "asterisk",
  "money",
  "currency-dollar",
  "translate",
  "floppy-disk",
  "calendar",
  "calendar-range",
  "calendar-blank",
  "tree-view",
  "github-logo",
  "dev-to-logo",
  "google-drive-logo",
  "instagram-logo",
  "reddit-logo",
  "brackets-round",
  "brackets-square",
  "code",
  "code-simple",
  "paragraph",
  "quotes",
  "gear",
  "gear-fine",
  "gear-six",
  "text-h-one",
  "text-h-two",
  "text-h-three",
  "text-h-four",
  "text-h-five",
  "text-h-six",
  "terminal-window",
  "stack",
  "list-checks",
  "code-block",
  "circuitry",
  "head-circuit",
  "cpu",
  "video-conference",
  "video-camera",
  "gift",
  "chats",
  "sparkle",
  "chat-centered-dots",
  "plus-circle",
  "cursor-click",
  "sign-out",
  "sign-in",
  "git-branch",
  "target",
  "smiley",
  "thumbs-up",
  "cloud-sun",
  "hash",
  "envelope",
  "link",
  "list-bullets",
  "list-dashes",
  "list-numbers",
  "tree-view",
  "timer",
  "file",
  "math-operations",
  "check-square",
  "check-square-offset",
  "map-pin",
  "book-open",
  "pencil-simple-slash",
  "stop",
  "text-align-left",
  "shapes",
  "sigma",
  "circle-dashed",

  "warning",
  "info",
  "lightbulb",
  "error",
  "device-mobile",
  "device-tablet",
  "desktop",
  "aperture",
  "android-logo",
  "apple-logo",
  "windows-logo",
  "linux-logo",
  "chrome-logo",
  "infinity",
  "rss",
  "rss-simple",
  "piggy-bank",
  "bicycle",
  "umbrella-simple",
  "coffee",
  "armchair",
  "bank",
  "currency-circle-dollar",
  "note-blank",
  "clipboard",
  "command",
  "sidebar",
  "chalkboard-simple",
  "cloud",
  "cloud-check",
  "wallet",
  "scroll",
  "columns",
  "rows",
  "sliders",
  "slideshow",
  "rectangle",
  "square",
  "steps",
  "rectangles-two",
  "push-pin-slash",
  "push-pin-simple-slash",
  "alarm",

  //Charts
  "chart-bar",
  "chart-bar-horizontal",
  "chart-line",
  "chart-polar",
  "chart-donut",
  "chart-scatter",
  "chart-line-up",
  "chart-line-down",
  "chart-pie",
  "presentation-chart"
];

export const phosphorRatingIcons = [
  "star",
  "fire",
  "fire-simple",
  "heart",
  "heart-straight",
  "book",
  "bookmark-simple",
  "push-pin",
  "push-pin-simple",
  "lightbulb",
  "lightbulb-filament",
  "lightning",
  "confetti",
  "medal",
  "trophy",
  "currency-dollar-simple",
  "currency-btc",
  "drop-simple",

  "smiley",
  "smiley-meh",
  "smiley-sad",
  "smiley-wink",
  "smiley-x-eyes",
  "smiley-nervous",
  "hand-peace",
  "hand-fist",
  "hand-heart",

  "thumbs-up",
  "thumbs-down",
  "arrow-fat-up",
  "arrow-fat-down",
  "plus-circle",
  "minus-circle",

  "circle",
  "diamond",
  "pentagon",
  "hexagon",
  "octagon",
  "hourglass-simple",

  "flag",
  "flag-checkered",
  "flag-pennant",
  "flag-banner",
  "asterisk",

  "person-simple",
  "person-simple-hike",
  "person-simple-bike",
  "person-simple-run",
  "person-simple-walk",
  "person-simple-ski",
  "person-simple-snowboard",
  "person-simple-swim",
  "person-simple-tai-chi",

  "airplane-tilt",
  "campfire",
  "map-pin",
  "footprints",
  "island",
  "mountains",
  "motorcycle",
  "globe-stand",

  "planet",
  "sun",
  "moon",
  "rocket",
  "rocket-launch",
  "snowflake",

  "balloon",
  "paint-brush",
  "paragraph",
  "pen-nib",
  "quotes",
  "puzzle-piece",
  "flower",
  "plant",
  "potted-plant",
  "music-notes",
  "film-reel",
  "film-slate",
  "bone",
  "paw-print",
  "crown-simple",
  "bowl-steam",
  "avocado",
  "orange"
];

const hugeiconsIcons = [
  "code",
  "solid-line-01",
  "equal-sign",
  "layout-table-02",
  "left-to-right-list-bullet",
  "left-to-right-list-number",
  "check-list",
  "paragraph",
  "quote-up",
  "summation-01",
  "heading-01",
  "heading-02",
  "heading-03",
  "heading-04",
  "sidebar-right"
];

const logos = [
  //Used in Markdown embed placeholder
  "google-drive",
  "youtube-icon",
  "google-maps",
  "replit-icon",
  "gitlab",
  "figma",
  "typeform-icon",

  "medium-icon",
  "stackoverflow-icon",
  "quora",
  "linkedin-icon",
  "facebook",
  "reddit-icon"
];

const simpleIcons = ["wikipedia", "googledocs", "abstract", "mixpanel"];

const svgSpinnersIcons = ["90-ring-with-bg", "3-dots-fade", "180-ring-with-bg"];

const heroiconsIcons = ["cog", "rectangle-group", "rectangle-stack"];
const heroiconsSolid = heroiconsIcons.map((icon) => icon + "-solid");

const letsIconsIcons = ["color-picker", "color-mode-light"];

const remixIcons = ["sketching"];

const proIcons = ["send"];

const fa6BrandsIcons = ["unsplash"];

const materialSymbolsLightIcons = ["keyboard-hide-outline-rounded"];

const f7Icons = ["keyboard-chevron-compact-down"];

const fluentIcons = ["keyboard-dock-20-regular"];

const fluentEmojiIcons = [
  "astronaut",
  "globe-showing-europe-africa",
  "glowing-star",
  "rocket",
  "potted-plant"
];

const tablerIcons = ["keyboard-show"];

const uilIcons = ["keyboard-hide"];

export const iconSets = {
  hugeicons: hugeiconsIcons,
  "svg-spinners": svgSpinnersIcons,
  heroicons: [...heroiconsIcons, ...heroiconsSolid],
  "lets-icons": letsIconsIcons,
  ri: remixIcons,
  proicons: proIcons,
  "simple-icons": simpleIcons,
  logos,
  "fa6-brands": fa6BrandsIcons,
  "material-symbols-light": materialSymbolsLightIcons,
  f7: f7Icons,
  fluent: fluentIcons,
  "fluent-emoji": fluentEmojiIcons,
  tabler: tablerIcons,
  uil: uilIcons
};

export const phIcons = {
  base: [...phosphorIcons, ...phosphorRatingIcons],
  light: [...phosphorIcons, ...phosphorRatingIcons].map(
    (icon) => icon + "-light"
  ),
  fill: [...phosphorIcons, ...phosphorRatingIcons].map((icon) => icon + "-fill")
};
