const phosphorIcons = [
  // Star variants
  "star",
  "star-half",

  // Navigation and Arrows
  "arrow-left",
  "arrow-right",
  "arrow-up",
  "arrow-down",
  "arrow-up-right",
  "arrow-down-left",
  "arrow-elbow-down-left",
  "arrow-elbow-right-up",
  "arrow-bend-down-left",
  "arrows-left-right",
  "arrows-out",
  "arrows-out-simple",
  "arrows-out-line-horizontal",
  "arrows-in-line-horizontal",
  "arrows-clockwise",

  // UI Controls
  "x",
  "x-circle",
  "x-bold",
  "plus",
  "minus-circle",
  "check",
  "check-bold",
  "check-circle",
  "dots-three-vertical",
  "dots-six-vertical",
  "dots-six-vertical-bold",
  "dots-six",

  // Media and Files
  "image",
  "video",
  "music-note",
  "file",
  "file-pdf",
  "file-csv",
  "file-html",
  "file-txt",
  "file-zip",
  "file-doc",
  "file-ppt",
  "file-xls",

  // Actions
  "crop",
  "highlighter",
  "highlighter-circle",
  "bookmark-simple",
  "bookmarks",
  "download-simple",
  "upload",
  "trash",
  "archive",
  "pencil-simple",
  "pencil-simple-line",
  "eye",
  "eye-slash",
  "copy",
  "link",
  "link-break",
  "faders",
  "sliders-horizontal",

  // Logos and Brands
  "x-logo",
  "youtube-logo",
  "amazon-logo",
  "discord-logo",
  "markdown-logo",

  // Layout and View
  "table",
  "tabs",
  "squares-four",
  "square-split-horizontal",
  "align-left-simple",
  "align-top-simple",
  "align-right-simple",
  "bounding-box",

  // Status and Info
  "info",
  "question",
  "lock",
  "lock-open",
  "lock-simple",
  "circle",
  "circle-bold",
  "circles-four",

  // Misc
  "book",
  "book-open-text",
  "brain",
  "bird",
  "butterfly",
  "caret-down",
  "caret-up",
  "cube",
  "database",
  "globe",
  "graph",
  "house",
  "keyboard",
  "leaf",
  "lightbulb",
  "magic-wand",
  "map-trifold",
  "note",
  "palette",
  "person-simple",
  "rocket",
  "share",
  "tag",
  "terminal",
  "text",
  "chat",
  "chat-teardrop-text",
  "clock",
  "clock-countdown",
  "git-fork",
  "gradient",
  "list",
  "magnifying-glass",
  "microphone",
  "pause",
  "play",
  "camera",
  "at",
  "asterisk",
  "money",
  "currency-dollar",
  "translate",
  "arrow-arc-left",
  "floppy-disk",
  "calendar",
  "calendar-range",
  "calendar-blank",
  "tree-view",
  "github-logo",
  "dev-to-logo",
  "google-drive-logo",
  "instagram-logo",
  "reddit-logo",
  "brackets-round",
  "code",
  "code-simple",
  "paragraph",
  "quotes",
  "gear",
  "gear-fine",
  "gear-six",
  "text-h-one",
  "text-h-two",
  "text-h-three",
  "text-h-four",
  "text-h-five",
  "text-h-six",
  "terminal-window",
  "stack",
  "list-checks",
  "code-block",
  "circuitry",
  "head-circuit",
  "cpu",
  "video-conference",
  "video-camera",
  "gift",
  "chats",
  "sparkle",
  "chat-centered-dots",
  "plus-circle",
  "cursor-click",
  "sign-out",
  "git-branch",
  "target",
  "smiley",
  "thumbs-up",
  "cloud-sun",
  "hash",
  "envelope",
  "link",
  "caret-circle-down",
  "list-bullets",
  "list-dashes",
  "list-numbers",
  "tree-view",
  "timer",
  "file",
  "math-operations",
  "check-square-offset",
  "map-pin",
  "caret-right",
  "book-open",
  "arrow-elbow-down-right",
  "pencil-simple-slash",
  "stop",
  "text-align-left",
  "shapes",
  "sigma",
  "circle-dashed",
  "arrow-u-up-left",
  "arrow-counter-clockwise",
  "warning",
  "info",
  "lightbulb",
  "error",
  "device-mobile",
  "device-tablet",
  "desktop",
  "aperture",
  "android-logo",
  "apple-logo",
  "windows-logo",
  "linux-logo",
  "chrome-logo",
  "arrow-clockwise",
  "caret-left"
];

export const phosphorRatingIcons = [
  "star",
  "fire",
  "fire-simple",
  "heart",
  "heart-straight",
  "book",
  "bookmark-simple",
  "push-pin",
  "push-pin-simple",
  "lightbulb",
  "lightbulb-filament",
  "lightning",
  "confetti",
  "medal",
  "trophy",
  "currency-dollar-simple",
  "currency-btc",
  "drop-simple",

  "smiley",
  "smiley-meh",
  "smiley-sad",
  "smiley-wink",
  "smiley-x-eyes",
  "smiley-nervous",
  "hand-peace",
  "hand-fist",
  "hand-heart",

  "thumbs-up",
  "thumbs-down",
  "arrow-fat-up",
  "arrow-fat-down",
  "plus-circle",
  "minus-circle",

  "circle",
  "diamond",
  "pentagon",
  "hexagon",
  "octagon",
  "hourglass-simple",

  "flag",
  "flag-checkered",
  "flag-pennant",
  "flag-banner",
  "asterisk",

  "person-simple",
  "person-simple-hike",
  "person-simple-bike",
  "person-simple-run",
  "person-simple-walk",
  "person-simple-ski",
  "person-simple-snowboard",
  "person-simple-swim",
  "person-simple-tai-chi",

  "airplane-tilt",
  "campfire",
  "map-pin",
  "footprints",
  "island",
  "mountains",
  "motorcycle",
  "globe-stand",

  "planet",
  "sun",
  "moon",
  "rocket",
  "rocket-launch",
  "snowflake",

  "balloon",
  "paint-brush",
  "paragraph",
  "pen-nib",
  "quotes",
  "puzzle-piece",
  "flower",
  "plant",
  "potted-plant",
  "music-notes",
  "film-reel",
  "film-slate",
  "bone",
  "paw-print",
  "crown-simple",
  "bowl-steam",
  "avocado",
  "orange"
];

const hugeiconsIcons = [
  "code",
  "solid-line-01",
  "equal-sign",
  "layout-table-02",
  "left-to-right-list-bullet",
  "left-to-right-list-number",
  "check-list",
  "paragraph",
  "quote-up",
  "summation-01",
  "heading-01",
  "heading-02",
  "heading-03",
  "heading-04"
];

const logos = [
  //Used in Markdown embed placeholder
  "google-drive",
  "youtube-icon",
  "google-maps",
  "replit-icon",
  "gitlab",
  "figma",
  "typeform-icon",

  "medium-icon",
  "stackoverflow-icon",
  "quora",
  "linkedin-icon",
  "facebook",
  "reddit-icon"
];

const simpleIcons = ["wikipedia", "googledocs", "abstract", "mixpanel"];

const svgSpinnersIcons = ["90-ring-with-bg", "3-dots-fade", "180-ring-with-bg"];

const heroiconsIcons = ["cog"];

const letsIconsIcons = ["color-picker", "color-mode-light"];

const remixIcons = ["sketching"];

const proIcons = ["send"];

const fa6BrandsIcons = ["unsplash"];

export const iconSets = {
  hugeicons: hugeiconsIcons,
  "svg-spinners": svgSpinnersIcons,
  heroicons: heroiconsIcons,
  "lets-icons": letsIconsIcons,
  ri: remixIcons,
  proicons: proIcons,
  "simple-icons": simpleIcons,
  logos,
  "fa6-brands": fa6BrandsIcons
};

export const phIcons = {
  base: [...phosphorIcons, ...phosphorRatingIcons],
  light: [...phosphorIcons].map((icon) => icon + "-light"),
  fill: [...phosphorIcons, ...phosphorRatingIcons].map((icon) => icon + "-fill")
};
