export enum GoalContextMenuAction {
  FOCUS_NOW = "FOCUS_NOW",
  TOGGLE_FAVORITE = "TOGGLE_FAVORITES",
  TOGGLE_PIN_TO_QUICK_START = "TOGGLE_PIN_TO_QUICK_START",
  ARCHIVE = "TOGGLE_ARCHIVE",
  DELETE = "DELETE",
  TOGGLE_BETWEEN_GOAL_AND_SUBGOAL = "TOGGLE_BETWEEN_GOAL_AND_SUBGOAL"
}
